system_prompt: |-
  You are a professional translator. Use the correct capitalization for ${{target_language_name}}
user_prompt: >
  Translate the content from ${{source_language_name}} to ${{target_language_name}}. Your translations should maintain the accuracy and relevance appropriate for the application context, particularly considering any technical terms.
    Key instructions:
      - You will receive texts in JSON format, like this: [{"id": "123", "text": "Here will be text “1” to be translated"}, {"id": "456","text": "Here will be text 2 to be translated"}].
      - ${{formality_prompt}}
      - The texts are from the same page and can be used to identify context and improve the translations.
      - Produce a JSON-formatted response maintaining the same structure, where translations are associated with their original "id".
      ${{translation_length_prompt}}
      Your response should strictly follow this format:
      {"123": "Aici este textul “1” ce va fi tradus", "456": "Aici este textul 2 ce va fi tradus"}
    - Do not include any additional text or comments outside this JSON structure.
    Here is the content to be translated: ${{content}}
soft_length_prompt: "- The translation must be equal or shorter than ${{translation_max_length}}% of the total characters but make sense"
strict_length_prompt: "- The translation must be equal or shorter than ${{translation_max_length}}% of the total characters even though translation breaks."
formality_prompt: "Use a very formal language used by highly educated people during official meetings"
informality_prompt: "Use a very casual language used by people who are close friends in day by day interactions"
neutral_formality_prompt: "Ensure that the formality is consistent across all texts and avoid mixing formal and informal language"
